#%RAML 0.8
---
title: File with 12 Resources. \
        Six of them have 1 level of nested Resources. 
            \Of those six, 
                \two of them have 4 levels of nesting, 
                \two of them have 3 levels of nesting and 
                \last two have 2 levels of nesting.
/pais1:
    /durango:
/pais2:
    /puebla:
/pais3:
    /tlaxcala:
/pais4:
    /yucatán:
/pais5:
    /quintanaroo:
/pais6:
    /veracruz:
/pais7:
    /michoacan:
        /municipio1:
            /colonia1:
                /calle1:
/pais8:
    /oaxaca:
        /municipio2:
            /colonia2:
                /calle2:
/pais9:
    /guerrero:
        /municipio3:
            /colonia3:
/pais10:
    /colima:
        /municipio4:
            /colonia4:
/pais11:
    /chihuahua:
        /municipio5:
        
/pais12:
    /tamaulipas:
        /municipio6:
    