#%RAML 0.8
---
title: File with 4 Resources, all of them with 1 nested Resource                                 and 1 of them with 2 nested levels
/holanda:
    /hestado1:
    /hestado2:
    /hestado3:
    /hestado4:
        /hmunicipio1:
